almost ready to check
GiyasovNikita/esoft_hw_5 pull request #1
Opened 2024-05-17 21:44 UTC by GiyasovNikita

Выполнил почти всё по заданию
По работе- можно было разбить на ещё более меньшие блоки-компоненты, не добавил в контекст сохранение состояний фильтров и сортировки

2024-05-25 20:53 UTC, Unaccommodating requested changes
Мне нравится твоя работа

2024-05-25 20:53 UTC, Unaccommodating commented on hw_5/src/components/commentsSection/CommentsSection.jsx
> +        addComment(filmId, comment);
можно надобавлять пустых комментариев?

2024-05-25 20:53 UTC, Unaccommodating commented on hw_5/src/layout/sidebar/Sidebar.jsx
> +                {console.log(watchLater)}
не забыл убрать?)

2024-05-25 20:53 UTC, Unaccommodating commented on hw_5/src/components/filmDetails/FilmDetails.jsx
> +                console.log(response);
console.log(response);

2024-06-22 23:04 UTC, RuslanLebj commented
Имбища бро, просто раскидал эту домашку, выстегнул жестко😲

2024-11-05 15:59 UTC, merged